before_install:
# 安装 matplotlib
- sudo pip install matplotlib
- sudo apt-get install graphviz 
- sudo apt-get install python-tk

# git 设置
- git config --global user.name "James Hopbourn"
- git config --global user.email "jameshopbourn@hotmail.com"

# 安装字体
- mkdir -p public
- mkdir -p ~/.local/share/fonts 
- mv SimHei.ttf ~/.local/share/fonts/

script:
#- chmod 777 build.sh
#- ./build.sh
- python Demo.py
- python Chinese.py
- dot -Tpng Gov.dot -o Gov.png
- dot -Tpng FamilyTree.dot -o FamilyTree.png
- mv *.png public

# 成功之后进入 public 目录将 public 目录内的内容上传到 master resource 分支
after_success:
- cd  public
- git init
- git add .
- git commit -m "Travis CI Auto Builder"
- git push --force https://${token}@github.com/JamesHopbourn/matplotlib-with-travis.git HEAD:resource 
